# CICADA analysis parameters
# Analysis : Widefield PSTH

analysis_class: CicadaWidefieldPsth
analysis_module: cicada_analysis.Petersen_lab_plugins.Widefield.cicada_widefield_psth
results_path: C:/Users/rdard/Documents/new_cicada_tests/analysis_results  # type:dir | MANDATORY
roi_response_series: {PB177_20240525_124055: [ophys, brain_grid_fluorescence, dff0_grid_traces], PB177_20240527_135745: [
    ophys, brain_grid_fluorescence, dff0_grid_traces], PB177_20240528_093711: [ophys,
    brain_grid_fluorescence, dff0_grid_traces], PB177_20240529_121819: [ophys, brain_grid_fluorescence,
    dff0_grid_traces], PB177_20240530_113408: [ophys, brain_grid_fluorescence, dff0_grid_traces],
  PB177_20240531_104515: [ophys, brain_grid_fluorescence, dff0_grid_traces], PB177_20240606_104234: [
    ophys, brain_grid_fluorescence, dff0_grid_traces], PB177_20240607_161204: [ophys,
    brain_grid_fluorescence, dff0_grid_traces], PB178_20240529_101445: [ophys, brain_grid_fluorescence,
    dff0_grid_traces], PB178_20240607_115237: [ophys, brain_grid_fluorescence, dff0_grid_traces],
  PB178_20240608_132641: [ophys, brain_grid_fluorescence, dff0_grid_traces], PB185_20240823_102701: [
    ophys, brain_grid_fluorescence, dff0_grid_traces], PB185_20240830_105945: [ophys,
    brain_grid_fluorescence, dff0_grid_traces], PB185_20240831_123411: [ophys, brain_grid_fluorescence,
    dff0_grid_traces], PB187_20240806_132010: [ophys, brain_grid_fluorescence, dff0_grid_traces],
  PB187_20240807_091702: [ophys, brain_grid_fluorescence, dff0_grid_traces], PB187_20240808_105328: [
    ophys, brain_grid_fluorescence, dff0_grid_traces], PB187_20240809_111335: [ophys,
    brain_grid_fluorescence, dff0_grid_traces], PB188_20240821_170100: [ophys, brain_grid_fluorescence,
    dff0_grid_traces], PB188_20240822_153551: [ophys, brain_grid_fluorescence, dff0_grid_traces],
  PB188_20240823_113645: [ophys, brain_grid_fluorescence, dff0_grid_traces], PB188_20240824_130819: [
    ophys, brain_grid_fluorescence, dff0_grid_traces], PB189_20240820_155808: [ophys,
    brain_grid_fluorescence, dff0_grid_traces], PB189_20240821_142007: [ophys, brain_grid_fluorescence,
    dff0_grid_traces], PB189_20240822_172840: [ophys, brain_grid_fluorescence, dff0_grid_traces]}  #  
plots_to_do: [wf_psth_full_plot]  # Plot(s) to do
epochs_to_do: [non-rewarded, rewarded]  # Select epoch(s) to do widefield analysis
center_on_epochs: false  # use epoch transition as center
trials_list: [auditory_hit_trial, auditory_miss_trial]  # Events
align_to: Stim  # Align on
merge_trial_type: false  # Merge all events
cell_types_to_do: ["(0.5, 4.5)", "(-2.5, 2.5)", "(2.5, 1.5)", "(-3.5, 1.5)", "(-2.5, 0.5)", "(1.5, 5.5)", "(-0.5, 4.5)", "(-1.5, 2.5)", "(-0.5, 0.5)", "(2.5, 0.5)", "(0.5, 5.5)", "(2.5, 2.5)", "(2.5, 5.5)", "(0.5, 1.5)", "(1.5, 2.5)", "(-2.5, 4.5)", "(2.5, 3.5)", "(-0.5, 3.5)", "(0.5, 2.5)", "(-0.5, 5.5)", "(-3.5, 4.5)", "(0.5, 3.5)", "(-1.5, 1.5)", "(-0.5, 1.5)", "(-1.5, 3.5)", "(-3.5, 2.5)", "(1.5, 3.5)", "(2.5, 4.5)", "(-2.5, 3.5)", "(-1.5, 5.5)", "(1.5, 4.5)", "(0.5, 0.5)", "(-3.5, 5.5)", "(-1.5, 4.5)", "(1.5, 0.5)", "(1.5, 1.5)", "(-2.5, 5.5)", "(-1.5, 0.5)", "(-0.5, 2.5)", "(-3.5, 0.5)", "(-3.5, 3.5)", "(-2.5, 1.5)"]  # cell_types_to_do
psth_start: 100  # Range of psth (ms) before event
psth_stop: 200  # Range of psth (ms) after event
subtract_baseline: true  # Subtract baseline
save_formats: [png]  # Formats in which to save the figures
dpi: 300  # Dpi (Dots per inches)
width_fig: 15  # Width figure
height_fig: 8  # Height figure
xkcd_mode: false  # Turn on xkcd sketch-style drawing mode
verbose: true  # Verbose
